import { Transaction } from '../types';

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  // 2025 Jan
  {
    id: 'sample_01',
    date: '2025-01-05',
    description: 'Salário Mensal',
    originalDescription: 'TED 237.0001 FOLHA PAGTO EMPRESA LTDA',
    amount: 11500.0,
    category: 'Salário & Receitas',
    paymentMethod: 'Transferência / TED',
    sourceFile: 'Controle Financeiro lindo2.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_02',
    date: '2025-01-06',
    description: 'Aluguel & Condomínio',
    originalDescription: 'PIX TRANSF IMOBILIARIA NOVO LAR',
    amount: -3400.0,
    category: 'Moradia & Contas',
    paymentMethod: 'PIX',
    sourceFile: 'Controle Financeiro lindo2.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_03',
    date: '2025-01-08',
    description: 'Conta de Luz',
    originalDescription: 'PAGTO ELETRON COBRANCA ENEL DISTRIB SP',
    amount: -224.5,
    category: 'Moradia & Contas',
    paymentMethod: 'Boleto',
    sourceFile: 'extrato_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_04',
    date: '2025-01-10',
    description: 'Supermercado Pão de Açúcar',
    originalDescription: 'COMPRA CARTAO VISA PAO DE ACUCAR 1230',
    amount: -680.9,
    category: 'Alimentação',
    paymentMethod: 'Cartão de Débito',
    sourceFile: 'extrato_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_05',
    date: '2025-01-12',
    description: 'iFood Refeição',
    originalDescription: 'COMPRA CARTAO IFOOD *RESTAURANTE',
    amount: -78.5,
    category: 'Alimentação',
    paymentMethod: 'Cartão de Crédito',
    sourceFile: 'fatura_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_06',
    date: '2025-01-15',
    description: 'Uber Corridas',
    originalDescription: 'COMPRA CARTAO UBER *TRIP SAO PAULO',
    amount: -145.2,
    category: 'Transporte',
    paymentMethod: 'Cartão de Crédito',
    sourceFile: 'fatura_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_07',
    date: '2025-01-18',
    description: 'Posto Shell Combustível',
    originalDescription: 'COMPRA CARTAO POSTO SHELL ALAMEDA',
    amount: -250.0,
    category: 'Transporte',
    paymentMethod: 'Cartão de Débito',
    sourceFile: 'extrato_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_08',
    date: '2025-01-20',
    description: 'Farmácia Droga Raia',
    originalDescription: 'COMPRA CARTAO DROGA RAIA 0945',
    amount: -134.8,
    category: 'Saúde & Farmácia',
    paymentMethod: 'Cartão de Débito',
    sourceFile: 'extrato_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_09',
    date: '2025-01-22',
    description: 'Netflix & Spotify',
    originalDescription: 'COMPRA CARTAO NETFLIX.COM BRASIL',
    amount: -55.9,
    category: 'Lazer & Assinaturas',
    paymentMethod: 'Cartão de Crédito',
    sourceFile: 'fatura_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_10',
    date: '2025-01-25',
    description: 'Aplicação Tesouro Selic',
    originalDescription: 'APLICACAO TESOURO DIRETO BANCO ITAU',
    amount: -2500.0,
    category: 'Investimentos',
    paymentMethod: 'Transferência / TED',
    sourceFile: 'extrato_itau_jan2025.xlsx',
    isAutoCategorized: true,
  },

  // 2025 Feb
  {
    id: 'sample_11',
    date: '2025-02-05',
    description: 'Salário Mensal',
    originalDescription: 'TED 237.0001 FOLHA PAGTO EMPRESA LTDA',
    amount: 11500.0,
    category: 'Salário & Receitas',
    paymentMethod: 'Transferência / TED',
    sourceFile: 'extrato_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_12',
    date: '2025-02-06',
    description: 'Aluguel & Condomínio',
    originalDescription: 'PIX TRANSF IMOBILIARIA NOVO LAR',
    amount: -3400.0,
    category: 'Moradia & Contas',
    paymentMethod: 'PIX',
    sourceFile: 'extrato_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_13',
    date: '2025-02-11',
    description: 'Carrefour Mercado',
    originalDescription: 'COMPRA CARTAO CARREFOUR HIPER',
    amount: -840.1,
    category: 'Alimentação',
    paymentMethod: 'Cartão de Débito',
    sourceFile: 'extrato_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_14',
    date: '2025-02-14',
    description: 'Jantar Restaurante',
    originalDescription: 'COMPRA CARTAO OUTBACK STEAKHOUSE SP',
    amount: -289.0,
    category: 'Alimentação',
    paymentMethod: 'Cartão de Crédito',
    sourceFile: 'fatura_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_15',
    date: '2025-02-18',
    description: 'Posto Ipiranga',
    originalDescription: 'COMPRA CARTAO POSTO IPIRANGA MORUMBI',
    amount: -240.0,
    category: 'Transporte',
    paymentMethod: 'Cartão de Débito',
    sourceFile: 'extrato_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_16',
    date: '2025-02-24',
    description: 'PIX Trabalho Extra / Consultoria',
    originalDescription: 'PIX RECEBIDO JOAO TECH CONSULTORIA',
    amount: 1800.0,
    category: 'Salário & Receitas',
    paymentMethod: 'PIX',
    sourceFile: 'extrato_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_17',
    date: '2025-02-26',
    description: 'Aplicação CDB Itaú 100% CDI',
    originalDescription: 'APLICACAO CDB DI ITAU UNIBANCO',
    amount: -3000.0,
    category: 'Investimentos',
    paymentMethod: 'Transferência / TED',
    sourceFile: 'extrato_itau_fev2025.xlsx',
    isAutoCategorized: true,
  },

  // 2025 Mar
  {
    id: 'sample_18',
    date: '2025-03-05',
    description: 'Salário Mensal',
    originalDescription: 'TED 237.0001 FOLHA PAGTO EMPRESA LTDA',
    amount: 11500.0,
    category: 'Salário & Receitas',
    paymentMethod: 'Transferência / TED',
    sourceFile: 'extrato_itau_mar2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_19',
    date: '2025-03-06',
    description: 'Aluguel & Condomínio',
    originalDescription: 'PIX TRANSF IMOBILIARIA NOVO LAR',
    amount: -3400.0,
    category: 'Moradia & Contas',
    paymentMethod: 'PIX',
    sourceFile: 'extrato_itau_mar2025.xlsx',
    isAutoCategorized: true,
  },
  {
    id: 'sample_20',
    date: '2025-03-08',
    description: 'PIX Transferência Avulsa',
    originalDescription: 'PIX TRANSF MARCOS VINICIUS SILVA',
    amount: -120.0,
    category: 'Outros',
    paymentMethod: 'PIX',
    sourceFile: 'extrato_itau_mar2025.xlsx',
    isAutoCategorized: false,
  },
  {
    id: 'sample_21',
    date: '2025-03-10',
    description: 'Pão de Açúcar Supermercado',
    originalDescription: 'COMPRA CARTAO PAO DE ACUCAR LOJA 40',
    amount: -712.3,
    category: 'Alimentação',
    paymentMethod: 'Cartão de Débito',
    sourceFile: 'extrato_itau_mar2025.xlsx',
    isAutoCategorized: true,
  },
];
